/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ConexionDB;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author herna
 */
public class pantalla_principal extends javax.swing.JFrame {

    /**
     * Creates new form pantalla_principañ
     */
    public pantalla_principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mensuales = new javax.swing.JButton();
        diario = new javax.swing.JButton();
        semanales = new javax.swing.JButton();
        IngresosMensuales = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        repDiario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Menu Principal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 140, 40));

        jButton1.setText("ingresar un dato nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        mensuales.setText("Gastos mensuales");
        mensuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mensualesActionPerformed(evt);
            }
        });
        getContentPane().add(mensuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        diario.setText("Gastos diarios");
        diario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diarioActionPerformed(evt);
            }
        });
        getContentPane().add(diario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, -1));

        semanales.setText("Gastos semanales");
        semanales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semanalesActionPerformed(evt);
            }
        });
        getContentPane().add(semanales, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        IngresosMensuales.setText("Ingresos mensuales");
        IngresosMensuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresosMensualesActionPerformed(evt);
            }
        });
        getContentPane().add(IngresosMensuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jButton2.setText("salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, -1, -1));

        repDiario.setText("Reportes");
        repDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repDiarioActionPerformed(evt);
            }
        });
        getContentPane().add(repDiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DatosPersonales dp = new DatosPersonales();
        dp.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mensualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mensualesActionPerformed
        int i = 1;
        while(i == 1){
        JTextField field1 = new JTextField();
        JTextField field2 = new JTextField();
        JTextField field3 = new JTextField();
        
        Object[] fields = { "Mes del gasto(entre 1 y 12)", field1,"Tipo de gasto mensual", field2, "Monto del gasto mensual", field3};

        JOptionPane.showConfirmDialog(null, fields, "Gastos mensuales", JOptionPane.OK_CANCEL_OPTION);
        int temp1 = Integer.parseInt(field1.getText());
        
        
         try{                 
                    ConexionBase conectado = new ConexionBase();
                    Connection con1 = conectado.getConnection();
                    Statement st= con1.createStatement();
                    String SQLGuardar= "INSERT INTO GASTOSMENSUALES(id_gasto_m,tipo_gasto_m,gasto_m)VALUES(?,?,?)";
                    PreparedStatement pst = con1.prepareCall(SQLGuardar);
                    
                    pst.setString(1,field1.getText());
                    pst.setString(2,field2.getText());
                    pst.setString(3,field3.getText());
                    
                    int n = pst.executeUpdate();
                    
                if (n>0){
                    JOptionPane.showMessageDialog(null,"Datos guardados correctamente\n");
                    pst.close();
                    i = Integer.parseInt(JOptionPane.showInputDialog("si quiers continuar ingresa 1\n para salir ingresa 0;"));
                }
                    
                    
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null,"Datos guardados erroneamente"+ ex);
                }
        
        }
    }//GEN-LAST:event_mensualesActionPerformed

    private void diarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diarioActionPerformed
        int i = 1;
        while(i == 1){
        JTextField field1 = new JTextField();
        JTextField field2 = new JTextField();
        JTextField field3 = new JTextField();
        
        Object[] fields = { "dia del gasto(entre 1 y 7)", field1,"Tipo de gasto diario", field2, "Monto del gasto diario", field3};

        JOptionPane.showConfirmDialog(null, fields, "Gastos diario", JOptionPane.OK_CANCEL_OPTION);
        
        int temp1 = Integer.parseInt(field1.getText());
        
         try{                 
                    ConexionBase conectado = new ConexionBase();
                    Connection con1 = conectado.getConnection();
                    Statement st= con1.createStatement();
                    String SQLGuardar= "INSERT INTO GASTOSDIARIOS(id_gasto_d,tipo_gasto_d,gasto_d)VALUES(?,?,?)";
                    PreparedStatement pst = con1.prepareCall(SQLGuardar);
                    
                    pst.setString(1,field1.getText());
                    pst.setString(2,field2.getText());
                    pst.setString(3,field3.getText());
                    
                    int n = pst.executeUpdate();
                    
                if (n>0){
                    JOptionPane.showMessageDialog(null,"Datos guardados correctamente\n");
                    pst.close();
                    
                     i = Integer.parseInt(JOptionPane.showInputDialog("si quiers continuar ingresa 1\n para salir ingresa 0;"));
                    
                    
                }
                    
                    
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null,"Datos guardados erroneamente"+ ex);
                }}
    }//GEN-LAST:event_diarioActionPerformed

    private void semanalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semanalesActionPerformed
       
        int i =1;
        while (i==1){
        JTextField field1 = new JTextField();
        JTextField field2 = new JTextField();
        JTextField field3 = new JTextField();
        
        Object[] fields = { "semana(entre 1 y 4 )", field1,"Tipo de gasto semanal", field2, "Monto del gasto semanal", field3};

        JOptionPane.showConfirmDialog(null, fields, "Gastos semanales", JOptionPane.OK_CANCEL_OPTION);
        int temp1 = Integer.parseInt(field1.getText());
        
       
         try{                 
                    ConexionBase conectado = new ConexionBase();
                    Connection con1 = conectado.getConnection();
                    Statement st= con1.createStatement();
                    String SQLGuardar= "INSERT INTO GASTOSSEMANALES(id_gasto_s,tipo_gasto_s,gasto_s)VALUES(?,?,?)";
                    PreparedStatement pst = con1.prepareCall(SQLGuardar);
                    
                    pst.setString(1,field1.getText());
                    pst.setString(2,field2.getText());
                    pst.setString(3,field3.getText());
                    
                    int n = pst.executeUpdate();
                    
                if (n>0){
                    JOptionPane.showMessageDialog(null,"Datos guardados correctamente\n");
                    pst.close();
                    i = Integer.parseInt(JOptionPane.showInputDialog("si quiers continuar ingresa 1\n para salir ingresa 0;"));
                }
                    
                    
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null,"Datos guardados erroneamente"+ ex);
                }}
    }//GEN-LAST:event_semanalesActionPerformed

    private void IngresosMensualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresosMensualesActionPerformed
        
                JTextField field1 = new JTextField();
        JTextField field2 = new JTextField();
        JTextField field3 = new JTextField();
        
        Object[] fields = { "Id de ingreso ", field1,"Tipo ingreso ", field2, "Monto ingreso", field3};

        JOptionPane.showConfirmDialog(null, fields, "Ingresos mensuales", JOptionPane.OK_CANCEL_OPTION);
        
         try{                 
                    ConexionBase conectado = new ConexionBase();
                    Connection con1 = conectado.getConnection();
                    Statement st= con1.createStatement();
                    String SQLGuardar= "INSERT INTO INGRESOSMENSUALES(id_ingreso,tipo_ingreso,monto_ingreso)VALUES(?,?,?)";
                    PreparedStatement pst = con1.prepareCall(SQLGuardar);
                    
                    pst.setString(1,field1.getText());
                    pst.setString(2,field2.getText());
                    pst.setString(3,field3.getText());
                    
                    int n = pst.executeUpdate();
                    
                if (n>0){
                    JOptionPane.showMessageDialog(null,"Datos guardados correctamente\n");
                    pst.close();
                }
                    
                    
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null,"Datos guardados erroneamente"+ ex);
                }
    }//GEN-LAST:event_IngresosMensualesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void repDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repDiarioActionPerformed
        // TODO add your handling code here:
        Reportes rp = new Reportes();
        rp.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_repDiarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantalla_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IngresosMensuales;
    private javax.swing.JButton diario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton mensuales;
    private javax.swing.JButton repDiario;
    private javax.swing.JButton semanales;
    // End of variables declaration//GEN-END:variables
}
